### ISSUE TITLE
Does graphql-batch allow for any sort of composable joins?

### ISSUE THREAD

**Issue by D1plo1d** [Shopify/graphql-batch#1]
Hey, not sure if this is the right project for this but I've been trying to figure out graphql in Ruby and the big issue I can't seem to figure out is how you go from a composed graphQL asking for all sorts of associations to a single SQL query loading all those associations via SQL joins.

Do the good people of Shopify have a solution for this particular problem yet? I get that it's early days still. Would this be in scope for graphql-batch?

**Comment by dylanahsmith** [comment]
I haven't thought much about what the best way to handle loading in multiple with joins would be, since we primarily use preloading rather than eager loading with joins.  This means that you would use a separate query for each table, which works well for caching with [identity cache](https://github.com/shopify/identity_cache), and avoids problems from trying to join a lot of associated tables together.

I think the solution would end up being similar to a field selection optimization, where you would need to look at the child selections, since they influence the query.  graphql-ruby provides the AST node on the context (https://github.com/rmosolgo/graphql-ruby/issues/6#issuecomment-137880889), which seems to be the way to do this for now.

I'm going to close this, because I think it is out of scope for this library.

**Comment by D1plo1d** [comment]
@dylanahsmith Thanks for the response. I can see how identity cache would make this a non-issue for Shopify.
