### ISSUE TITLE
through association loader order issue

### ISSUE THREAD

**Issue by zhangyonguu** [Shopify/graphql-batch#111]
Hi:

My graphql-ruby version is 1.9.6, and I use the [association loader](https://github.com/Shopify/graphql-batch/blob/master/examples/association_loader.rb) in the example directory

I have these models: Route, RoutesStop, and Stop

Route has this association:
`has_many :stops, -> { order 'route_stops.order' }, through: :route_stops`

When I use association loader to load `stops` field in my RouteType, I got this kind of issue:
`ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  missing FROM-clause entry for table "route_stops"` 

and the sql it actually execute is: 
`SELECT "stops".* FROM "stops" WHERE "stops"."id" IN (1, 12) ORDER BY route_stops.order`

How can I unscope the order scope of ActiveRecord::Relation to avoid the exception OR what can I do to deal with the exception, under the premise of not *removing* the scope in the has_many relationship definition

Thanks!

**Comment by dylanahsmith** [comment]
Is this just an active record issue?  Does it cause the same issue if you try to preload the association using active record directly?  E.g. `Route.where(id: route_ids).preload(:stops).to_a`.

I think the problem is that active record uses two queries to batch preload a through association and you are using a raw SQL string for the order, so active record doesn't even know that the route_stops table needs to be referenced by the query.  You could try using [references](https://github.com/rails/rails/blob/v6.0.2.2/activerecord/lib/active_record/relation/query_methods.rb#L202-L215) to make sure active record know the route_stops table is referenced.
