### ISSUE TITLE
Cannot re-use loaders

### ISSUE THREAD

**Issue by Mange** [Shopify/graphql-batch#21]
I was trying to reuse a loader, but if the second load provides a different input id it will crash with `GraphQL::Batch::BrokenPromiseError: Promise wasn't fulfilled after all queries were loaded`.

Example:

```ruby
loader = SomeLoader.for
loader.load(1).sync # First load
loader.load(1).sync # Everything's okay. Record already loaded.

loader.load(2).sync # Crashes.
# gems/promise.rb-0.7.1/lib/promise.rb:84:in `block in reject'
# gems/promise.rb-0.7.1/lib/promise.rb:114:in `dispatch'
# gems/promise.rb-0.7.1/lib/promise.rb:82:in `reject'
# gems/graphql-batch-0.2.4/lib/graphql/batch/executor.rb:33:in `wait'
# gems/graphql-batch-0.2.4/lib/graphql/batch/promise.rb:4:in `wait'
# gems/promise.rb-0.7.1/lib/promise.rb:64:in `sync'
```

It crashes before reaching the `#perform` method at all.

Is this by design? I think the README should mention it in that case.

**Comment by Mange** [comment]
Since `for` re-uses instances when the arguments are identical, this always happens even if using the full loader call (`SomeLoader.for(x).load(2).sync`).

**Comment by dylanahsmith** [comment]
A loader wasn't really designed to be re-used, since it was meant to perform a single batch load.  I would prefer to just give a more useful error message in this case.

Why are you re-using a loader for multiple batch loads?  The point of the library is to batch loads.

My concern with supporting this is that this is a base class for loaders, so derived classes would also need to worry about the loader being re-used.  Thus I don't want to support this unless there is a real use case for it.

The reason this doesn't work is the `for` method registers the loader with the executor rather than the `load` method.  It is done like this because the callbacks for a batch load might register more loads, so I want those new loads to be associated with a new loader to avoid changing the state of the loader in the middle of it being performed.

**Comment by Mange** [comment]
I got this while I was implementing a loader that composed two other loaders, loading each ID from either other loader depending on a few conditions. I was fighting this error a long time before I figured it out, which is why I wanted clarification. 
The fault itself was with my tests, where I set up a loader and then tried to load two different things in the same example. 
I adjusted the tests and the problem stopped.
