### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by jsdnxx** [Shopify/graphql-batch#40]
I just saw that version 0.3 was released- congratulations! Is there a list of what has changed? I would recommend also checking it into the repo in a changelog file.

Cheers

**Comment by dylanahsmith** [comment]
https://github.com/Shopify/graphql-batch/compare/v0.2.5...v0.3.0 for a full list of changes.  https://github.com/Shopify/graphql-batch/pull/36 is a breaking change but should only affect test code.  The main feature is support for https://github.com/rmosolgo/graphql-ruby/blob/master/guides/schema/lazy_execution.md which was released after the last release of this library, so I should update the README to recommend the use of that feature instead of the graphql-batch execution strategies.

**Comment by sjchmiela** [comment]
> recommend the use of that feature instead of the graphql-batch execution strategies.

and `graphql-ruby` recommends use of graphql-batch…

> The example above is simple and has some shortcomings. Consider the graphql-batch gem for a robust solution to batched resolution.

Which should one use then?

**Comment by dylanahsmith** [comment]
I'm not saying to stop using graphql-batch, just that instead of doing

```ruby
MySchema = GraphQL::Schema.define do
  query MyQueryType
end
MySchema.query_execution_strategy = GraphQL::Batch::ExecutionStrategy
MySchema.mutation_execution_strategy = GraphQL::Batch::MutationExecutionStrategy
```

you would do

```ruby
MySchema = GraphQL::Schema.define do
  query MyQueryType
  lazy_resolve(Promise, :sync)
  instrument(:query, GraphQL::Batch::Setup)
end
```

GraphQL::Batch::ExecutionStrategy and GraphQL::Batch::MutationExecutionStrategy will be deprecated then removed since they rely on method overrides which make them fragile to changes in graphql-ruby

**Comment by sjchmiela** [comment]
Ah, all right, that I couldn't even think of. :)

**Comment by jsdnxx** [comment]
Ah, I didn't even think to use GitHub's compare :) Thanks!
