### ISSUE TITLE
Keeping order of records

### ISSUE THREAD

**Issue by firedev** [Shopify/graphql-batch#44]
How would one go to keep the order of records in the output? I have an `ordered` scope for `has_many`, but batch loading throws it off, and I don't want to sort in front-end.

**Comment by dylanahsmith** [comment]
I don't see why it wouldn't keep the same ordering.  If you are doing multiple loads using `load_many` then it uses `Promise.all` and keeps the same ordering.  If it is a single load, then it would use the same object passed into `fulfill` in your batch loaders `perform` method.

**Comment by firedev** [comment]
Hi, thanks for your reply, I am using a foreign key loader:
```
class Parent < ApplicationRecord
  has_many :chilren, -> { ordered }, inverse_of: :parent
end

ParentType = GraphQL::ObjectType.define do
  field :children do
    type types[Types::ChildrenType]
    resolve ->(obj, _args, _ctx) {
      ForeignKeyLoader.for(Children, :parent_id).load([obj.id])
    }
  end
```
Actually I have fixed it by using `ForeignKeyLoader.for(Children.ordered, :parent_id).load([obj.id])`

But is there a better way?

**Comment by dylanahsmith** [comment]
You still haven't provided an example of what your batch loader is even doing.  Considering that you aren't passing a record into the loader, I'm guessing you are doing something like `Children.where(parent_id: parent_id)` instead of just loading an association on the record, so the scope on your has_many association isn't going to do anything.

We use an association loader instead as mentioned in https://github.com/Shopify/graphql-batch/issues/24#issuecomment-277331157

**Comment by firedev** [comment]
Thanks.
