### ISSUE TITLE
KeyError, key not found

### ISSUE THREAD

**Issue by maxtechera** [Shopify/graphql-batch#50]
I'm using the base example with RecordLoader, like this in a resolver
`Loaders::RecordLoader.for(Product).load(Product.ids)`

I'm getting this error: 
`KeyError (key not found: 6)`

`6` is the first id loaded. I think its somehow related to `promise_for(load_key)` in loader.rb.

Has anyone had this happen?

**Comment by dylanahsmith** [comment]
That happens when Loaders::RecordLoader#perform calls fulfill with a key that wasn't among the keys passed into perform.

The problem is that you are passing an array of ids in as a single key, which it doesn't find using the id of a single record.  Instead use `Loaders::RecordLoader.for(Product).load_many(Product.ids)`

**Comment by nattfodd** [comment]
Sorry for bumping it, but I have the same error following the guide from README, and I use proper method (`load`).

```ruby
module BatchLoader
  class Records < GraphQL::Batch::Loader
    def initialize(model)
      @model = model
    end

    def perform(ids)
      @model.where(person_id: ids).each { |record| fulfill(record.id, record) }
      ids.each { |id| fulfill(id, nil) unless fulfilled?(id) }
    end
  end
end
```
