### ISSUE TITLE
Association Loader with scopes

### ISSUE THREAD

**Issue by danlewis** [Shopify/graphql-batch#77]
Can graphql-batch be used to load associations with scopes?

I was hoping updating the preload_association method in the AssociationLoader example might do the job like so:

```
  def preload_association(records)
    ::ActiveRecord::Associations::Preloader.new.preload(records, @association_name, @scope)
  end
```

However this doesn't appear to work and reverts to n+1 queries when used in graphql. It does work when used outside graphql in a rails console strangely enough. e.g.

```
ActiveRecord::Associations::Preloader.new.preload( Place.all, :opening_times, OpeningTime.where(x: 'y') )
```

**Comment by dylanahsmith** [comment]
I would recommend against using the third argument (preload_scope) of ActiveRecord::Associations::Preloader#preload for filtering, since I think that would result in the association being loaded with that filter applied, in which case some other code may use the association to get unfiltered results but instead get filtered results.  Also, be aware that ActiveRecord::Associations::Preloader is undocumented and that argument was probably only added to support preloading through associations, so internal refactoring of rails could break your code.

Use another approach instead, e.g.
* Use `.reject` to filter the loaded association result
* Add another association that applies the filter
* Use a separate GraphQL::Batch::Loader that doesn't rely on memoization

**Comment by hisea** [comment]
Hi @dylanahsmith 

We are facing the same issue as @danlewis.

We tried option 1 and the size of data we have actually made the batch load slower than the N+1 version of it since ruby was doing a lot of array filtering. and option 2 is not really possible since the scope we want to apply takes an argument that passed by the GraphQL Query.

I'm wondering if you can please provide an example of option3 and maybe we can try with our dataset and see if this will solve our issue.

Thanks.

**Comment by danlewis** [comment]
I ended up using option 2 but had to limit what my API could do as a result which was less than ideal.

An example of a separate GraphQL::Batch::Loader would be really helpful!

**Comment by hisea** [comment]
@dylanahsmith thanks for your reply.

In our case, we need to load a many-to-many association through an joint table, and we want to apply some scope on this association as well.

**Comment by ifiatlux** [comment]
I ran into the same problem and came up with the following solution:

```ruby
module Loaders
  class AssociationLoader < GraphQL::Batch::Loader
    def self.validate(model, association_name)
      new(model, association_name)
      nil
    end

    def initialize(model, association_name, where: nil)
      @model = model
      @where = where
      @association_name = association_name
      validate
    end

    def load(record)
      raise TypeError, "#{@model} loader can't load association for #{record.class}" unless record.is_a?(@model)
      return Promise.resolve(read_association(record)) if association_loaded?(record)
      super
    end

    # We want to load the associations on all records, even if they have the same id
    def cache_key(record)
      record.object_id
    end

    def perform(records)
      preload_association(records)
      records.each { |record| fulfill(record, read_association(record)) }
    end

    private

    def validate
      unless @model.reflect_on_association(@association_name)
        raise ArgumentError, "No association #{@association_name} on #{@model}"
      end
    end

    def preload_association(records)
      ::ActiveRecord::Associations::Preloader.new.preload(records, @association_name, get_scope)
    end

    def read_association(record)
      record.public_send(@association_name)
    end

    def association_loaded?(record)
      record.association(@association_name).loaded?
    end

    private

    def get_scope
      scope = nil
      if @where.present?
        scope = @model.reflect_on_association(@association_name).class_name.constantize
        @where.each {|q| scope = scope.where(*q)}
      end
      scope
    end
  end
end
```

This class can be called like this:

```ruby
Loaders::AssociationLoader.for(SomeModel, :some_relation, where: where).load(record)
```

And `where` should be a list containing items in the style of these two:

```ruby
# 1. custom query
where << ["created_at between ? and ?", start_date, end_date]
#2. auto query
where << {id: some_id}
```

**Comment by joshforbes** [comment]
I wanted to throw another solution up here. The goal was to be able to use my defined scopes and pass them to a loader.  Like this:

```ruby
Loaders::AssociationLoader.for(User, :calls, Call.active).load(record)
```

The following takes ideas from the AssociationLoaders specified here and from the `graphql-preload` gem https://github.com/ConsultingMD/graphql-preload (which seems to no longer be maintained)

```ruby
module Loaders
  class AssociationLoader < GraphQL::Batch::Loader
    def self.for(model, association_name, scope = nil)
      # I believe this will address the loader being reused when it shouldn't be
      loader_key = loader_key_for(model, association_name, scope.try(:to_sql))
      executor = GraphQL::Batch::Executor.current

      executor.loader(loader_key) { new(model, association_name, scope) }
    end

    def initialize(model, association_name, scope = nil)
      @model = model
      @association_name = association_name
      @scope = scope
    end

    def load(record)
      unless record.is_a?(model)
        raise TypeError, "#{model} loader can't load association for #{record.class}"
      end
      return Promise.resolve(read_association(record)) if association_loaded?(record)

      super
    end

    def cache_key(record)
      record.object_id
    end

    def perform(records)
      preload_association(records)
      records.each { |record| fulfill(record, read_association(record)) }
    end

    private

    attr_reader :model, :association_name, :scope

    def preload_association(records)
      ::ActiveRecord::Associations::Preloader.new.preload(records, association_name, preload_scope)
    end

    # this is from the graphql preloader gem
    def preload_scope
      return nil unless scope

      reflection = model.reflect_on_association(association_name)
      raise ArgumentError, 'Cannot specify preload_scope for polymorphic associations' if
        reflection.polymorphic?

      scope if scope.try(:klass) == reflection.klass
    end

    def read_association(record)
      record.public_send(association_name)
    end

    def association_loaded?(record)
      record.association(association_name).loaded?
    end
  end
end
```

Hope it is helpful for someone.

**Comment by dylanahsmith** [comment]
@ifiatlux & @joshforbes both of your examples demonstrate what I was warning about in https://github.com/Shopify/graphql-batch/issues/77#issuecomment-388565859 which is that you are loading the association with filtered results.  That seems dangerous because if other code uses that association without the scope or with a different scope, then one of those callers will get the association with the wrong scope.

It would be safer to define another association that has the desired filtering (e.g. `active_calls` instead of using the `calls` association with the `Call.active` scope).

Another option would be to reset the association after loading it in the batch loader and use the promise result instead of relying on the association being loaded on the record itself.  Additionally, it will be necessary to handle the case where the association is already loaded (i.e. without a scope) in which case you would have to apply the scope in memory on the loaded records (e.g. simulate a where filter).  This would be difficult to do for an arbitrary scope (e.g. a scope with a join or arbitrary SQL) so I would recommend only supporting a subset of these features and raising if a scope isn't supported.

**Comment by joshforbes** [comment]
Thanks for the reply. Interesting. So I was thinking that using the sql of the scope for the loader key would prevent the loader from being reused for different scopes - thereby triggering a new query.

```ruby
    def self.for(model, association_name, scope = nil)
      # I believe this will address the loader being reused when it shouldn't be
      loader_key = loader_key_for(model, association_name, scope.try(:to_sql))
      executor = GraphQL::Batch::Executor.current

      executor.loader(loader_key) { new(model, association_name, scope) }
    end
```

But I guess I misunderstood what is happening there :cry:

**Comment by Anle90** [comment]
ran into this issue with a has_many association where I wanted to add an ordered scope. Not sure what to do here either

**Comment by alexander37137** [comment]
I have another solution, but it should be used accurately

```
# frozen_string_literal: true

class Loaders::ScopeLoader < GraphQL::Batch::Loader
  def initialize(model)
    @model = model
  end

  def perform(scopes)
    values = scopes.map { |scope| @model.where(scope) }.reduce { |acc, current| acc.or(current) }.to_a
    scopes.each { |scope| fulfill(scope, find_results(values, scope)) }
  end

  private

  def find_results(records, scope)
    records.select do |record|
      scope.all? { |key, value| record.send(key) == value }
    end
  end
end
```

There can be problems with comparision between passed scoped and model fields

**Comment by 23tux** [comment]
@joshforbes Wondering if you ran into some issues by using the SQL as the loader key

```
loader_key = loader_key_for(model, association_name, scope.try(:to_sql))
```

I have a similar use case where I try to do two things:

1. Use CanCan's `#accessible_by(ability)` to only get authorized results from a `has_many` relation
2. Use arguments in GraphQL that are applied via `where(active: true)`

First, I think CanCan would not be a problem, because the same ability is used throughout the whole request and is applied on all associations, so another part of the code using the same association would not be affected (I hope I'm right).

Second, when you either use the arguments that are passed onto `#where` OR the SQL itself with `loader_key`, I can't think of an example where that might be a problem. So I'm curious if you did run into some problems using the SQL as `loader_key`.

Also @dylanahsmith opinion would be much appreciated if there could be any problem with that approach, as he raised my concerns with this whole approach.

**Comment by dylanahsmith** [comment]
> So I was thinking that using the sql of the scope for the loader key would prevent the loader from being reused for different scopes - thereby triggering a new query.

Sure, it would prevent the loader from being re-used, but you are loading the results of that loader into an association on a record that could be used in other code that doesn't use the same scope.  For example, if you used that loader on the same record(s) and association with different scopes, then the result from the first performed load would be preloaded into the association and re-used by the other load with the same scope.

**Comment by nerdylocks** [comment]
@hisea were you able to solve for your case? (Preloading a scoped collection in the many to many case)

**Comment by etaba** [comment]
I think what @dylanahsmith is saying is that by using the `preload_scope` argument you risk poisoning the association for other callers.
Once you preload the association:
`ActiveRecord::Associations::Preloader.new.preload(users, :calls, Call.active);`
from then on _any_ time you do something like:
`users.first.calls`
... you will only get the preloaded "active" calls, even if you didn't expect them. The only way to get the true results will be to reload the object. This is probably why the `preload_scope` argument is left out of the documentation. 
I think that if you treat the `users` carefully (i.e. make sure its associations are never called when you wouldn't want the preloaded scope applied to the results) it may be ok to use this approach, but i'm not sure.

**Comment by etaba** [comment]
This is what i have. It does use preload_scope but then resets the association cache upon fulfilling the promise:

`# frozen_string_literal: true

class AssociationLoader < GraphQL::Batch::Loader
  def self.for(model, association_name, scope = nil, order: {})
    loader_key = loader_key_for(model, association_name, scope.try(:to_sql), order: order)
    executor = GraphQL::Batch::Executor.current
    executor.loader(loader_key) { new(model, association_name, scope, order: order) }
  end

  def self.validate(model, association_name)
    new(model, association_name)
    nil
  end

  def initialize(model, association_name, scope = nil, order: {})
    @model = model
    @association_name = association_name
    @order = order
    @order = { **@order, id: :desc } unless @order.has_key?(:id) # Order last by ID (a unique column) for tie breaking if not provided
    @scope = scope
    validate
  end

  def load(record)
    raise TypeError, "#{@model} loader can't load association for #{record.class}" unless record.is_a?(@model)
    if scope_provided? && association_loaded?(record)
      # scope is present but association has probably already been preloaded without it
      # reset the association to clear the cache
      record.association(association_name).reset
    elsif association_loaded?(record)
      return Promise.resolve(read_association(record))
    end

    super
  end

  # We want to load the associations on all records, even if they have the same id
  def cache_key(record)
    record.object_id
  end

  def perform(records)
    preload_association(records)
    records.each { |record| fulfill(record, read_association(record)) }
  end

  # if we preloaded a scope into the association, we must reset the cache here so that further calls to the object's
  #  member are not poisoned
  def fulfill(parent, _)
    result = super
    parent.association(association_name).reset if scope_provided? && result.fulfilled? && parent.association(association_name).loaded?
    result
  end

  private

  attr_reader :model, :association_name, :scope, :order

  def scope_provided?
    scope.try(:to_sql).present?
  end

  def validate
    raise ArgumentError, "No association #{@association_name} on #{@model}" unless @model.reflect_on_association(@association_name)
  end

  def preload_scope
    return nil unless scope

    reflection = model.reflect_on_association(association_name)
    raise ArgumentError, 'Cannot specify preload_scope for polymorphic associations' if
      reflection.polymorphic?

    preload_scope = @order.present? ? scope.merge(reflection.klass.reorder(@order)) : scope

    preload_scope if preload_scope.try(:klass) == reflection.klass
  end

  def preload_association(records)
    # DANGER!
    # calling this with a preload_scope argument will cause Active Record to cache the scoped result of the associations
    # this can cause issues if the plain association is called on any of these records without the scope,
    #   because they will still get the scoped result
    ::ActiveRecord::Associations::Preloader.new.preload(records, association_name, preload_scope)
  end

  def read_association(record)
    if preload_scope
      # if scope provided, order is merged into it
      record.public_send(@association_name)
    else
      # else just dealing with an order
      record.public_send(@association_name).reorder(@order)
    end
  end

  def association_loaded?(record)
    record.association(@association_name).loaded?
  end
end
`

**Comment by tvillafane** [comment]
@etaba thanks for that!  I've lived in this thread the last two days and I'm very pleased with the results.

**Comment by jhirn** [comment]
I wish they'd bite the bullet and just provide a functional AssociationLoader but that's just me being lazy and not being grateful.

**Comment by jturkel** [comment]
You might be able to use the [goldiloader](https://github.com/salsify/goldiloader) gem to provide automatic eager loading depending on your use case. The biggest caveat is that all of the "owner" models need to be loaded in a single ActiveRecord query if you want their associations to be automatically eager loaded e.g.

```graphql
# Automatic eager loading of the Post#authors associations works because the Posts are loaded in a single query
query {
  blog(id: 1) {
    posts(first: 10) {
       nodes {
         author {
           name
         }
       }
    }
  }
}

# Automatic eager loading of the Post#authors associations doesn't work because the Posts are loaded in separate queries
query {
  post(id: 10) {
    author {
      name
    }
  }
  post(id: 11) {
    author {
      name
    }
  }
}
```

**Comment by kaka-ruto** [comment]
I followed how RedHat's TheForeman repo solved their AssociationLoader(they call it CollectionLoader) scoping issues and it worked for me. Haven't had any issues so far. The repo is open source so you can have a look https://github.com/theforeman/foreman/blob/e46a838b00/app/graphql/collection_loader.rb

The biggest difference is that their `read_association` method returns only 'records_by_owner' records
```
def read_association(preloader, record)
    preloader.records_by_owner[record] || []
end
```

**Comment by rsslldnphy** [comment]
Have been running into an issue with the `AssociationLoader` when used with a `has_one` association that makes use of `limit`, like this:

```ruby
class User < ActiveRecord::Base
    has_many :attendances
    has_one :last_attendance, -> { joins(:sessions).order("sessions.started_at desc").limit(1) }, class_name: "Attendance"
end

# elsewhere
AssociationLoader.for(User, :last_attendance).load(user)
```

If there is more than one user to load the `last_attendance` of, it doesn't work - I'm guessing (but haven't got my head round the code) because the limit is being applied to the query as a whole? Does this sound about right? Any workarounds anyone can think of? The `AssociationLoader` we're using is lifted from the examples in the repo.

**Comment by dylanahsmith** [comment]
Batching limit queries is outside the scope of the AssociationLoader example.  Try preloading an association with a limit query and you will see that it isn't something that Active Record supports.

**Comment by rsslldnphy** [comment]
In case it makes it easier, what I’m trying to find out is if there is _at least one_ attendance. I.e. have they ever been to a session before. Is this possible with graphql-batch? Thanks!

**Comment by rsslldnphy** [comment]
Thanks @dylanahsmith - appreciate your help. To clarify, I get that this specific approach to solving the problem won't work in graphql-batch due to the limitations of active record, I meant more to ask whether there is an alternative approach to solving the same problem that works better within the constraints of graphql-batch. I'll poke around and see if I can come up with anything.
